import { EntryStateIds } from "./entry-states.constants";
import { EntryTypeIds } from "./entry-types.constants"; // Adjust path if needed

/**
 * Seed data for the `entries` table
 *
 * IMPORTANT: Entry Relationship Mapping
 * - Entry IDs 1-5: BUNDLE entries (NEW state, supplier-based)
 * - Entry IDs 6-9: SERIES entries (NEW state, supplier-based)
 * - Entry ID 10: SERIES entry (RETURNED state, customer-based) - Returns original entry ID 6
 * - Entry IDs 11-14: ITEM entries (NEW state, supplier-based)
 * - Entry ID 15: ITEM entry (RETURNED state, customer-based) - Returns original entry ID 11
 *
 * For RETURNED entries:
 * - Use customerId instead of supplierId
 * - Must have corresponding records in returns table linking to original entries
 * - Customer information is required for processing returns
 */
export const BUNDLE_ENTRIES = [
  {
    id: 1,
    entryTypeId: EntryTypeIds.BUNDLE,
    entryStateId: EntryStateIds.NEW,
    quantity: 100,
    weight: "111.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "New bundle entry 1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    id: 2,
    entryTypeId: EntryTypeIds.BUNDLE,
    entryStateId: EntryStateIds.NEW,
    quantity: 200,
    weight: "222.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "New bundle entry 2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 2,
    isDeleted: false,
  },
  {
    id: 3,
    entryTypeId: EntryTypeIds.BUNDLE,
    entryStateId: EntryStateIds.NEW,
    quantity: 300,
    weight: "333.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "New bundle entry 3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 2,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    id: 4,
    entryTypeId: EntryTypeIds.BUNDLE,
    entryStateId: EntryStateIds.NEW,
    quantity: 400,
    weight: "444.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "New bundle entry 4",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 2,
    updatedBy: 2,
    isDeleted: false,
  },
  {
    id: 5,
    entryTypeId: EntryTypeIds.BUNDLE,
    entryStateId: EntryStateIds.NEW,
    quantity: 500,
    weight: "555.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "New bundle entry 5",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    id: 6,
    entryTypeId: EntryTypeIds.BUNDLE,
    entryStateId: EntryStateIds.NEW,
    quantity: 50,
    weight: "25.0",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "Bundle from supplier X",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 7,
    entryTypeId: EntryTypeIds.BUNDLE,
    entryStateId: EntryStateIds.NEW,
    quantity: 80,
    weight: "40.0",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "Bundle from supplier X",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
];

export const SERIES_ENTRIES = [
  {
    id: 8,
    entryTypeId: EntryTypeIds.SERIES,
    entryStateId: EntryStateIds.NEW,
    quantity: 100,
    weight: "111.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "New SERIES entry 1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 2,
    isDeleted: false,
  },
  {
    id: 9,
    entryTypeId: EntryTypeIds.SERIES,
    entryStateId: EntryStateIds.NEW,
    quantity: 200,
    weight: "222.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "New SERIES entry 2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 2,
    updatedBy: 1,
    isSent: true,
    isDeleted: false,
  },
  {
    id: 10,
    entryTypeId: EntryTypeIds.SERIES,
    entryStateId: EntryStateIds.NEW,
    quantity: 300,
    weight: "333.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "New SERIES entry 3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isSent: true,
    isDeleted: false,
  },
  {
    id: 11,
    entryTypeId: EntryTypeIds.SERIES,
    entryStateId: EntryStateIds.NEW,
    quantity: 400,
    weight: "444.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "New SERIES entry 4",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 2,
    updatedBy: 2,
    isDeleted: false,
  },
  {
    id: 12,
    entryTypeId: EntryTypeIds.SERIES,
    entryStateId: EntryStateIds.RETURNED,
    quantity: 500,
    weight: "555.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    customerId: 1, // Customer who returned this series
    description: "Returned SERIES entry 5",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 2,
    updatedBy: 1,
    isDeleted: false,
  },

  {
    id: 13,
    entryTypeId: EntryTypeIds.SERIES,
    entryStateId: EntryStateIds.NEW,
    quantity: 20,
    weight: "10.0",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "Series from supplier X",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 14,
    entryTypeId: EntryTypeIds.SERIES,
    entryStateId: EntryStateIds.NEW,
    quantity: 30,
    isTransferable: true,
    isSent: false,
    weight: "15.0",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "Series from supplier X",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 15,
    entryTypeId: EntryTypeIds.SERIES,
    entryStateId: EntryStateIds.NEW,
    quantity: 30,
    isTransferable: true,
    isSent: false,
    weight: "15.0",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "Series from supplier X",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 16,
    entryTypeId: EntryTypeIds.SERIES,
    entryStateId: EntryStateIds.NEW,
    quantity: 30,
    isTransferable: true,
    isSent: false,
    weight: "15.0",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "Series from supplier X",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
];

export const ITEM_ENTRIES = [
  {
    id: 17,
    entryTypeId: EntryTypeIds.ITEM,
    entryStateId: EntryStateIds.NEW,
    quantity: 100,
    weight: "111.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    supplierId: 1,
    description: "New ITEM entry 1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 2,
    isDeleted: false,
  },
  {
    id: 18,
    entryTypeId: EntryTypeIds.ITEM,
    entryStateId: EntryStateIds.NEW,
    quantity: 200,
    weight: "222.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    supplierId: 1,
    description: "New ITEM entry 2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 2,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    id: 19,
    entryTypeId: EntryTypeIds.ITEM,
    entryStateId: EntryStateIds.NEW,
    quantity: 300,
    weight: "333.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    supplierId: 1,
    description: "New ITEM entry 3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    id: 20,
    entryTypeId: EntryTypeIds.ITEM,
    entryStateId: EntryStateIds.NEW,
    quantity: 400,
    weight: "444.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    supplierId: 1,
    description: "New ITEM entry 4",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 2,
    updatedBy: 2,
    isDeleted: false,
  },
  {
    id: 21,
    entryTypeId: EntryTypeIds.ITEM,
    entryStateId: EntryStateIds.RETURNED,
    quantity: 500,
    weight: "555.123",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    customerId: 2, // Customer who returned this item
    description: "Returned ITEM entry 5",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 2,
    updatedBy: 1,
    isDeleted: false,
  },

  {
    id: 22,
    entryTypeId: EntryTypeIds.ITEM,
    entryStateId: EntryStateIds.NEW,
    quantity: 1,
    weight: "0.3",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    supplierId: 1,
    description: "Item from supplier X",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 23,
    entryTypeId: EntryTypeIds.ITEM,
    entryStateId: EntryStateIds.NEW,
    quantity: 1,
    weight: "0.3",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    supplierId: 1,
    description: "Item from supplier X",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 24,
    entryTypeId: EntryTypeIds.ITEM,
    entryStateId: EntryStateIds.NEW,
    isTransferable: true,
    quantity: 1,
    weight: "0.3",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 2,
    supplierId: 1,
    description: "Item from supplier X",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
];

export const PKG_ENTRIES = [
  {
    id: 25,
    entryTypeId: EntryTypeIds.PACKAGE,
    entryStateId: EntryStateIds.NEW,
    quantity: 2,
    isTransferable: false,
    isSent: true,

    weight: "1.0",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    customerId: 1,
    description: "Returned ITEM entry 5",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 2,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    id: 26,
    entryTypeId: EntryTypeIds.PACKAGE,
    entryStateId: EntryStateIds.NEW,
    quantity: 1,
    isTransferable: false,
    isSent: true,

    weight: "0.3",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    customerId: 2,
    supplierId: 1,
    description: "Package W1 -> W2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 27,
    entryTypeId: EntryTypeIds.PACKAGE,
    entryStateId: EntryStateIds.NEW,
    quantity: 1,
    weight: "0.3",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    customerId: 3,
    supplierId: 1,
    description: "Package W1 -> W2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 28,
    entryTypeId: EntryTypeIds.PACKAGE,
    entryStateId: EntryStateIds.NEW,
    quantity: 1,
    weight: "0.3",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    customerId: 4,
    supplierId: 1,
    description: "Package W1 -> W2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 29,
    entryTypeId: EntryTypeIds.PACKAGE,
    entryStateId: EntryStateIds.NEW,
    quantity: 1,
    weight: "0.3",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    customerId: 3,
    supplierId: 1,
    description: "Package W1 -> W2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 30,
    entryTypeId: EntryTypeIds.PACKAGE,
    entryStateId: EntryStateIds.NEW,
    quantity: 1,
    weight: "0.3",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    customerId: 3,
    supplierId: 1,
    description: "Package W1 -> W2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 31,
    isTransferable: true,
    entryTypeId: EntryTypeIds.PACKAGE,
    entryStateId: EntryStateIds.NEW,
    quantity: 1,
    weight: "0.3",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    customerId: 3,
    supplierId: 1,
    description: "Package W1 -> W2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 32,
    isTransferable: true,
    entryTypeId: EntryTypeIds.PACKAGE,
    entryStateId: EntryStateIds.NEW,
    quantity: 1,
    weight: "0.3",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    customerId: 3,
    supplierId: 1,
    description: "Package W1 -> W2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 33,
    isTransferable: true,
    entryTypeId: EntryTypeIds.PACKAGE,
    entryStateId: EntryStateIds.NEW,
    quantity: 1,
    weight: "0.5",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    customerId: 2,
    supplierId: 1,
    description: "Package W1 -> W2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },
  {
    id: 34,
    isTransferable: true,
    entryTypeId: EntryTypeIds.PACKAGE,
    entryStateId: EntryStateIds.NEW,
    quantity: 1,
    weight: "0.5",
    date: new Date().toISOString().split("T")[0],
    imageUrl1: "https://example.com/image1.jpg",
    imageUrl2: "https://example.com/image2.jpg",
    warehouseId: 1,
    customerId: 3,
    supplierId: 1,
    description: "Package W1 -> W2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
    isDeleted: false,
  },

];

export const ENTRIES_DATA = [
  ...BUNDLE_ENTRIES,
  ...SERIES_ENTRIES,
  ...ITEM_ENTRIES,
  ...PKG_ENTRIES,
];
