export const BINS_DATA = [
  // Warehouse 1 — Rayon "1" (id=1), Shelf "A" (id=1)
  {
    shelfId: 1,
    rowNumber: 1,
    warehouseId: 1,
    locationCode: "1A1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    shelfId: 1,
    rowNumber: 2,
    warehouseId: 1,
    locationCode: "1A2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  // Warehouse 1 — Rayon "1" (id=1), Shelf "B" (id=2)
  {
    shelfId: 2,
    rowNumber: 1,
    warehouseId: 1,
    locationCode: "1B1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    shelfId: 2,
    rowNumber: 2,
    warehouseId: 1,
    locationCode: "1B2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  // Warehouse 1 — Rayon "2" (id=2), Shelf "A" (id=3)
  {
    shelfId: 3,
    rowNumber: 1,
    warehouseId: 1,
    locationCode: "2A1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    shelfId: 3,
    rowNumber: 2,
    warehouseId: 1,
    locationCode: "2A2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  // Warehouse 1 — Rayon "2" (id=2), Shelf "B" (id=4)
  {
    shelfId: 4,
    rowNumber: 1,
    warehouseId: 1,
    locationCode: "2B1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  // Warehouse 2 — Rayon "3" (id=3), Shelf "A" (id=5)
  {
    shelfId: 5,
    rowNumber: 1,
    warehouseId: 2,
    locationCode: "3A1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    shelfId: 5,
    rowNumber: 2,
    warehouseId: 2,
    locationCode: "3A2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  // Warehouse 2 — Rayon "3" (id=3), Shelf "B" (id=6)
  {
    shelfId: 6,
    rowNumber: 1,
    warehouseId: 2,
    locationCode: "3B1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    shelfId: 6,
    rowNumber: 2,
    warehouseId: 2,
    locationCode: "3B2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  // Warehouse 2 — Rayon "4" (id=4), Shelf "A" (id=7)
  {
    shelfId: 7,
    rowNumber: 1,
    warehouseId: 2,
    locationCode: "4A1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    shelfId: 7,
    rowNumber: 2,
    warehouseId: 2,
    locationCode: "4A2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  // Warehouse 2 — Rayon "4" (id=4), Shelf "B" (id=8)
  {
    shelfId: 8,
    rowNumber: 1,
    warehouseId: 2,
    locationCode: "4B1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  // Extra bins for testing pagination
  {
    shelfId: 99,
    rowNumber: 1,
    warehouseId: 1,
    locationCode: "1C1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
];
