export enum CategoryNames {
  MEN = "Men",
  WOMEN = "Women",
  KIDS = "Kids",
  ACCESSORIES = "Accessories",
  SHOES = "Shoes",
  ELECTRONICS = "Electronics",
}

export const CATEGORIES = [
  {
    name: CategoryNames.MEN,
    description: "Men's clothing and essentials",
    parentId: null,
    level: 1,
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    name: CategoryNames.WOMEN,
    description: "Women's clothing and essentials",
    parentId: null,
    level: 1,
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    name: CategoryNames.KIDS,
    description: "Kids and toddlers clothing",
    parentId: null,
    level: 1,
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    name: CategoryNames.ACCESSORIES,
    description: "Belts, wallets, hats, and more",
    parentId: null,
    level: 1,
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    name: CategoryNames.SHOES,
    description: "Sneakers, boots, heels, and sandals",
    parentId: null,
    level: 1,
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    name: CategoryNames.ELECTRONICS,
    description: "Phones, smartwatches, and tech gadgets",
    parentId: null,
    level: 1,
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
];
