/**
 * Customer codes enum for type safety and autocompletion
 */
export enum CustomerCode {
  CPK_A01 = "CPK_A01",
  CPK_A02 = "CPK_A02",
  CIN_A03 = "CPK_A03",
  CPK_A04 = "CPK_A04",
  CPK_C01 = "CPK_C01",
  CPK_C02 = "CPK_C02",
  CPK_C03 = "CPK_C03",
  CPK_C04 = "CPK_C04",
  CPK_C05 = "CPK_C05",
  CPK_C06 = "CPK_C06",
  CPK_C07 = "CPK_C07",
  CPK_C08 = "CPK_C08",
  CPK_C09 = "CPK_C09",
  CPK_C10 = "CPK_C10",
  CPK_C11 = "CPK_C11",
  CPK_C12 = "CPK_C12",
}

/**
 * Descriptions for customer codes (optional)
 */
export const CUSTOMER_CODE_DESCRIPTIONS: Record<CustomerCode, string> = {
  [CustomerCode.CPK_A01]: "Customer from Pakistan - A01",
  [CustomerCode.CPK_A02]: "Customer from Pakistan - A02",
  [CustomerCode.CIN_A03]: "Customer from India - A03",
  [CustomerCode.CPK_A04]: "Customer from Pakistan - A04",
  [CustomerCode.CPK_C01]: "Customer 1",
  [CustomerCode.CPK_C02]: "Customer 2",
  [CustomerCode.CPK_C03]: "Customer 3",
  [CustomerCode.CPK_C04]: "Customer 4",
  [CustomerCode.CPK_C05]: "Customer 5",
  [CustomerCode.CPK_C06]: "Customer 6",
  [CustomerCode.CPK_C07]: "Customer 7",
  [CustomerCode.CPK_C08]: "Customer 8",
  [CustomerCode.CPK_C09]: "Customer 9",
  [CustomerCode.CPK_C10]: "Customer 10",
  [CustomerCode.CPK_C11]: "Customer 11",
  [CustomerCode.CPK_C12]: "Customer 12",
};

/**
 * Seed data for the `customers` table
 */
export const CUSTOMERS_DATA = [
  {
    userId: 1,
    customerCode: CustomerCode.CPK_A01,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 2,
    customerCode: CustomerCode.CPK_A02,
    preferredPaymentMethodId: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 2,
    updatedBy: 2,
    isDeleted: false,
  },
  {
    userId: 3,
    customerCode: CustomerCode.CIN_A03,
    preferredPaymentMethodId: 3,
    isActive: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 3,
    updatedBy: 3,
    isDeleted: false,
  },
  {
    userId: 4,
    customerCode: CustomerCode.CPK_A04,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 5,
    customerCode: CustomerCode.CPK_C01,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 6,
    customerCode: CustomerCode.CPK_C02,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 7,
    customerCode: CustomerCode.CPK_C03,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 8,
    customerCode: CustomerCode.CPK_C04,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 9,
    customerCode: CustomerCode.CPK_C05,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 10,
    customerCode: CustomerCode.CPK_C06,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 11,
    customerCode: CustomerCode.CPK_C07,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 12,
    customerCode: CustomerCode.CPK_C08,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 13,
    customerCode: CustomerCode.CPK_C09,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 14,
    customerCode: CustomerCode.CPK_C10,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 15,
    customerCode: CustomerCode.CPK_C11,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
  {
    userId: 16,
    customerCode: CustomerCode.CPK_C12,
    preferredPaymentMethodId: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
  },
];
