/**
 * Entity types available in the application
 * Using enum for better type safety and autocompletion
 */
export enum EntityType {
  ENTITIES = "entities",
  OPERATIONS = "operations",
  ROLES = "roles",
  USERS = "users",
  EMPLOYEES = "employees",
  SUPPLIERS = "suppliers",
  CUSTOMERS = "customers",
  RETAILERS = "retailers",
  PAYMENT_METHODS = "payment_methods",
  DISCOUNTS = "discounts",
  WAREHOUSES = "warehouses",
  WAREHOUSE_TRANSFERS = "warehouse_transfers",
  WAREHOUSE_1 = "warehouse_1",
  WAREHOUSE_2 = "warehouse_2",
  ATTRIBUTES = "attributes",
  COLORS = "colors",
  SIZES = "sizes",
  PRODUCTS = "products",
  VARIANTS = "variants",
  VARIANT_IMAGES = "variant_images",
  ENTRIES = "entries",
  FAQS = "faqs",
  FILTERS = "filters",
  NOTIFICATIONS = "notifications",
  TESTIMONIALS = "testimonials",
  ABOUT_US = "about_us",
  BANNERS = "banners",
  CATEGORIES = "categories",
  NEW_ARRIVALS = "new_arrivals",
  ONGOING_GROUPS = "ongoing_groups",
  ONGOING_GROUP_REQUESTS = "ongoing_group_requests",
  REVIEWS = "reviews",
  PROMOTIONS = "promotions",
  SHIPPING_LABELS = "shipping_labels",
  TAGS = "tags",
  ORDERS = "orders",
}

/**
 * Provides descriptions for entity types
 */
export const ENTITY_DESCRIPTIONS: Record<EntityType, string> = {
  [EntityType.ENTITIES]: "Entities",
  [EntityType.OPERATIONS]: "Operations",
  [EntityType.ROLES]: "Roles",
  [EntityType.USERS]: "Users",
  [EntityType.EMPLOYEES]: "Employees",
  [EntityType.SUPPLIERS]: "Suppliers",
  [EntityType.CUSTOMERS]: "Customers",
  [EntityType.RETAILERS]: "Retailers",
  [EntityType.PAYMENT_METHODS]: "Payment Methods",
  [EntityType.DISCOUNTS]: "Discounts",
  [EntityType.WAREHOUSES]: "Warehouses",
  [EntityType.WAREHOUSE_TRANSFERS]: "Warehouse Transfers",
  [EntityType.WAREHOUSE_1]: "Warehouse 1",
  [EntityType.WAREHOUSE_2]: "Warehouse 2",
  [EntityType.ATTRIBUTES]: "Attributes",
  [EntityType.COLORS]: "Colors",
  [EntityType.SIZES]: "Sizes",
  [EntityType.PRODUCTS]: "Products",
  [EntityType.VARIANTS]: "Variants",
  [EntityType.VARIANT_IMAGES]: "Variant Images",
  [EntityType.ENTRIES]: "Entries",
  [EntityType.FAQS]: "Faqs",
  [EntityType.FILTERS]: "Filters",
  [EntityType.NOTIFICATIONS]: "Notifications",
  [EntityType.TESTIMONIALS]: "Testimonials",
  [EntityType.ABOUT_US]: "About Us",
  [EntityType.BANNERS]: "Banners",
  [EntityType.CATEGORIES]: "Categories",
  [EntityType.NEW_ARRIVALS]: "New Arrivals",
  [EntityType.ONGOING_GROUPS]: "Ongoing Groups",
  [EntityType.ONGOING_GROUP_REQUESTS]: "Ongoing Group Requests",
  [EntityType.REVIEWS]: "Reviews",
  [EntityType.PROMOTIONS]: "Promotions",
  [EntityType.SHIPPING_LABELS]: "Shipping Labels",
  [EntityType.TAGS]: "Tags",
  [EntityType.ORDERS]: "Orders",
};
