export const ORDER_ITEMS = [
  {
    orderId: 1,
    productId: 2,
    variantId: 3,
    quantity: 1,
    quantityPacked: 1, // Fully packed in package 1
    fulfillmentStatusId: 3, // fully_fulfilled
    unitPrice: "29.99",
    subTotal: "39.99",
    notes: "Seeds included notes for order items, id: 1",
    productName: "Sport Shoes",
    productCode: "DO_PK_A01_B1_P2",
    variantCode: "VAR-003",
    colorName: "Green",
    sizeName: "Extra Small",
    productImageUrl: "https://example.com/images/sport-shoes.jpg",
    createdBy: 1,
    updatedBy: 1,
  },
  {
    orderId: 1,
    productId: 4,
    variantId: 5,
    quantity: 2,
    quantityPacked: 2, // 1 in package 1, 1 in package 2
    fulfillmentStatusId: 3, // fully_fulfilled
    unitPrice: "15.5",
    subTotal: "31.0",
    notes: "Seeds included notes for order items, id: 1",
    productName: "Summer Dress",
    productCode: "DS_PK_A01_WOM_P1",
    variantCode: "VAR-005",
    colorName: "Orange",
    sizeName: "Extra Small",
    productImageUrl: "https://example.com/images/summer-dress.jpg",
    createdBy: 1,
    updatedBy: 1,
  },
  {
    orderId: 7,
    productId: 7,
    variantId: 6,
    quantity: 1,
    quantityPacked: 1, // Fully packed in package 3
    quantityAvailable: 1,
    fulfillmentStatusId: 3, // fully_fulfilled
    unitPrice: "100.00",
    subTotal: "101.00",
    notes: "Seeds included notes for order items, id: 7",
    productName: "Smart Watch",
    productCode: "DO_PK_A01_B3_P2",
    variantCode: "VAR-006",
    colorName: "Purple",
    sizeName: "Small",
    productImageUrl: "https://example.com/images/smart-watch.jpg",
    createdBy: 1,
    updatedBy: 1,
  },
  {
    orderId: 8,
    productId: 8,
    variantId: 7,
    quantity: 1,
    quantityPacked: 1, // Fully packed in package 4
    fulfillmentStatusId: 3, // fully_fulfilled
    unitPrice: "89.00",
    subTotal: "90.0",
    notes: "Seeds included notes for order items, id: 8",
    productName: "Laptop Bag",
    productCode: "DS_PK_A02_ACC_P1",
    variantCode: "VAR-007",
    colorName: "Pink",
    sizeName: "Extra Small",
    productImageUrl: "https://example.com/images/laptop-bag.jpg",
    createdBy: 1,
    updatedBy: 1,
  },
  {
    orderId: 9,
    productId: 2,
    variantId: 3,
    quantity: 2,
    quantityPacked: 0, // Not packed yet
    quantityAvailable: 1, // Only 1 available for packing
    fulfillmentStatusId: 1, // pending
    unitPrice: "29.99",
    subTotal: "59.98",
    notes: "Seeds included notes for order items, id: 9",
    productName: "Sport Shoes",
    productCode: "DO_PK_A01_B1_P2",
    variantCode: "VAR-003",
    colorName: "Green",
    sizeName: "Extra Small",
    productImageUrl: "https://example.com/images/sport-shoes.jpg",
    createdBy: 1,
    updatedBy: 1,
  },
  {
    orderId: 9,
    productId: 4,
    variantId: 5,
    quantity: 1,
    quantityPacked: 0, // Not packed yet
    quantityAvailable: 1,
    fulfillmentStatusId: 1, // pending
    unitPrice: "15.5",
    subTotal: "15.5",
    notes: "Seeds included notes for order items, id: 9",
    productName: "Summer Dress",
    productCode: "DS_PK_A01_WOM_P1",
    variantCode: "VAR-005",
    colorName: "Orange",
    sizeName: "Extra Small",
    productImageUrl: "https://example.com/images/summer-dress.jpg",
    createdBy: 1,
    updatedBy: 1,
  },
  {
    orderId: 10,
    productId: 7,
    variantId: 6,
    quantity: 1,
    quantityPacked: 0, // Not packed yet
    fulfillmentStatusId: 1, // pending
    unitPrice: "100.00",
    subTotal: "100.00",
    notes: "Seeds included notes for order items, id: 10",
    productName: "Smart Watch",
    productCode: "DO_PK_A01_B3_P2",
    variantCode: "VAR-006",
    colorName: "Purple",
    sizeName: "Small",
    productImageUrl: "https://example.com/images/smart-watch.jpg",
    createdBy: 1,
    updatedBy: 1,
  },
];
