export enum OrderStatusType {
  APPROVAL = "approval",
  PAYMENT_OF_ITEMS = "payment_of_items",
  ORDER_RECEIVE_BY_MANUFACTURER = "order_receive_by_manufacturer",
  ORDER_SHIPPED_BY_AGENT = "order_shipped_by_agent",
  PACKAGING = "packaging",
  PAYMENT_OF_KILO = "payment_of_kilo",
  ORDER_AT_STORE = "order_at_store",
  ORDER_ARRIVED_AT_LOCALE_CUSTOMS = "order_arrived_at_locale_customs",
  PAYMENT_FOR_DELIVERIES = "payment_for_deliveries",
  PENDING = "pending",
  PROCESSING = "processing",
  SHIPPED = "shipped",
  DELIVERED = "delivered",
  CANCELLED = "cancelled",
  RETURNED = "returned",
  REFUNDED = "refunded",
  PAYMENT = "payment",
  ORDER_PLACED = "order_placed",
  READY_FOR_FULFILLMENT = "ready_for_fulfillment",
}

export const OrderStatusTypeIds = {
  APPROVAL: 1,
  PAYMENT_OF_ITEMS: 2,
  ORDER_RECEIVE_BY_MANUFACTURER: 3,
  ORDER_SHIPPED_BY_AGENT: 4,
  PACKAGING: 5,
  PAYMENT_OF_KILO: 6,
  ORDER_AT_STORE: 7,
  ORDER_ARRIVED_AT_LOCALE_CUSTOMS: 8,
  PAYMENT_FOR_DELIVERIES: 9,
  PENDING: 10,
  PROCESSING: 11,
  SHIPPED: 12,
  DELIVERED: 13,
  CANCELLED: 14,
  RETURNED: 15,
  REFUNDED: 16,
  PAYMENT: 17,
  ORDER_PLACED: 18,
  READY_FOR_FULFILLMENT: 19,
} as const;

export const ORDER_STATUS_TYPE_DESCRIPTIONS: Record<OrderStatusType, string> = {
  [OrderStatusType.APPROVAL]: "Order is pending approval",
  [OrderStatusType.PAYMENT_OF_ITEMS]: "Payment for items is being processed",
  [OrderStatusType.ORDER_RECEIVE_BY_MANUFACTURER]: "Order has been received by manufacturer",
  [OrderStatusType.ORDER_SHIPPED_BY_AGENT]: "Order has been shipped by agent",
  [OrderStatusType.PACKAGING]: "Order is being packaged",
  [OrderStatusType.PAYMENT_OF_KILO]: "Payment per kilo is being processed",
  [OrderStatusType.ORDER_AT_STORE]: "Order is at the store",
  [OrderStatusType.ORDER_ARRIVED_AT_LOCALE_CUSTOMS]: "Order has arrived at local customs",
  [OrderStatusType.PAYMENT_FOR_DELIVERIES]: "Payment for deliveries is being processed",
  [OrderStatusType.PENDING]: "Order is waiting for confirmation",
  [OrderStatusType.PROCESSING]: "Order is being processed",
  [OrderStatusType.SHIPPED]: "Order has been shipped",
  [OrderStatusType.DELIVERED]: "Order has been delivered",
  [OrderStatusType.CANCELLED]: "Order has been cancelled",
  [OrderStatusType.RETURNED]: "Order has been returned",
  [OrderStatusType.REFUNDED]: "Order has been refunded",
  [OrderStatusType.PAYMENT]: "Payment is being processed",
  [OrderStatusType.ORDER_PLACED]: "Order has been placed",
  [OrderStatusType.READY_FOR_FULFILLMENT]: "Order is ready for fulfillment",
};
