import { OrderStatusTypeIds } from "./order-statuses.constants";
import { OrderTypeIds } from "./order-types.constants";

export enum OrdersNumber {
  ORD_202307_001 = "ORD_202307_001",
  ORD_202307_002 = "ORD_202307_002",
  ORD_202308_001 = "ORD_202308_001",
  ORD_202308_002 = "ORD_202308_002",
  ORD_202308_003 = "ORD_202308_003",
  ORD_202308_004 = "ORD_202308_004",
  ORD_202309_001 = "ORD_202309_001",
  ORD_202309_002 = "ORD_202309_002",
  ORD_202309_003 = "ORD_202309_003",
  ORD_202309_004 = "ORD_202309_004",
}

export const ORDERS = [
  {
    customerId: 1,
    orderCode: OrdersNumber.ORD_202307_001,
    orderDate: new Date().toISOString(),
    statusId: OrderStatusTypeIds.PENDING,
    fulfillmentStatusId: 2, // partially_fulfilled - some items packed across packages 1 and 2
    orderTypeId: 1,
    shippingAddressId: 1,
    shippingPriorityCodeId: 1,
    billingAddressId: 1,
    paymentMethodId: 1,
    subtotal: "99.99",
    taxAmount: "8.25",
    shippingAmount: "5.00",
    discountAmount: "10.00",
    totalAmount: "103.24",
    notes: "Please deliver between 9 AM and 5 PM.",
    version: 1,
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },

  {
    customerId: 2,
    orderCode: OrdersNumber.ORD_202307_002,
    orderDate: new Date().toISOString(),
    statusId: 2,
    fulfillmentStatusId: 1, // pending
    orderTypeId: 2,
    shippingAddressId: 2,
    shippingPriorityCodeId: 2,
    billingAddressId: 2,
    paymentMethodId: 2,
    subtotal: "149.99",
    taxAmount: "12.50",
    shippingAmount: "0.00",
    discountAmount: "15.00",
    totalAmount: "147.49",
    notes: "Gift wrap this order, please.",
    version: 1,
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    customerId: 1,
    orderCode: OrdersNumber.ORD_202308_001,
    orderDate: new Date().toISOString(),
    statusId: 1,
    fulfillmentStatusId: 1, // pending
    orderTypeId: 1,
    shippingAddressId: 1,
    shippingPriorityCodeId: 1,
    billingAddressId: 1,
    paymentMethodId: 1,
    subtotal: "79.99",
    taxAmount: "6.80",
    shippingAmount: "5.00",
    discountAmount: "0.00",
    totalAmount: "91.79",
    notes: "Leave package at the front door if not home.",
    version: 1,
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    customerId: 3,
    orderCode: OrdersNumber.ORD_202308_002,
    orderDate: new Date().toISOString(),
    statusId: 3,
    fulfillmentStatusId: 1, // pending
    orderTypeId: 2,
    shippingAddressId: 3,
    shippingPriorityCodeId: 3,
    billingAddressId: 3,
    paymentMethodId: 3,
    subtotal: "199.99",
    taxAmount: "16.50",
    shippingAmount: "10.00",
    discountAmount: "20.00",
    totalAmount: "206.49",
    notes: "Call upon arrival.",
    version: 1,
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    customerId: 4,
    orderCode: OrdersNumber.ORD_202308_003,
    orderDate: new Date().toISOString(),
    statusId: 1,
    fulfillmentStatusId: 1, // pending
    orderTypeId: 1,
    shippingAddressId: 5,
    shippingPriorityCodeId: 2,
    billingAddressId: 4,
    paymentMethodId: 5,
    subtotal: "129.99",
    taxAmount: "10.40",
    shippingAmount: "7.50",
    discountAmount: "5.00",
    totalAmount: "142.89",
    notes: "Please ensure all items are in stock before shipping.",
    version: 1,
    createdBy: 2,
    updatedBy: 2,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  { customerId: 4, orderCode: OrdersNumber.ORD_202308_004, orderDate: new Date().toISOString(), statusId: 2, fulfillmentStatusId: 1, orderTypeId: 2, shippingAddressId: 5, billingAddressId: 4, paymentMethodId: 5, subtotal: "89.99", taxAmount: "7.20", shippingAmount: "5.00", discountAmount: "0.00", totalAmount: "102.19", notes: "Deliver to the back entrance.", version: 1, createdBy: 2, updatedBy: 2, isDeleted: false, deletedAt: null, deletedBy: null },

  {
    customerId: 4,
    orderCode: OrdersNumber.ORD_202309_001,
    orderDate: new Date().toISOString(),
    statusId: 10,
    fulfillmentStatusId: 3, // fully_fulfilled - all items in package 3
    orderTypeId: 1,
    shippingAddressId: 5,
    shippingPriorityCodeId: 1,
    billingAddressId: 4,
    paymentMethodId: 5,
    subtotal: "100.0",
    taxAmount: "00.0",
    shippingAmount: "0.0",
    discountAmount: "0.0",
    totalAmount: "100.0",
    notes: "Please ensure all items are in stock before shipping.",
    version: 1,
    createdBy: 2,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  { customerId: 4, orderCode: OrdersNumber.ORD_202309_002, orderDate: new Date().toISOString(), statusId: 1, fulfillmentStatusId: 3, orderTypeId: 1, shippingAddressId: 5, billingAddressId: 4, paymentMethodId: 5, subtotal: "89.99", taxAmount: "0.0", shippingAmount: "0.0", discountAmount: "0.00", totalAmount: "89.99", notes: "Deliver to the back entrance.", version: 1, createdBy: 2, updatedBy: null, isDeleted: false, deletedAt: null, deletedBy: null },
  {
    customerId: 15,
    orderCode: OrdersNumber.ORD_202309_003,
    orderDate: new Date().toISOString(),
    statusId: OrderStatusTypeIds.READY_FOR_FULFILLMENT,
    fulfillmentStatusId: 1, // pending
    orderTypeId: OrderTypeIds.DIRECT_ORDER,
    shippingAddressId: 1,
    shippingPriorityCodeId: 1,
    billingAddressId: 1,
    paymentMethodId: 1,
    subtotal: "200.00",
    taxAmount: "10.00",
    shippingAmount: "5.00",
    discountAmount: "0.00",
    totalAmount: "215.00",
    notes: "Ready for fulfillment test order 1",
    version: 1,
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    customerId: 16,
    orderCode: OrdersNumber.ORD_202309_004,
    orderDate: new Date().toISOString(),
    statusId: OrderStatusTypeIds.READY_FOR_FULFILLMENT,
    fulfillmentStatusId: 1, // pending
    orderTypeId: OrderTypeIds.DIRECT_ORDER,
    shippingAddressId: 2,
    shippingPriorityCodeId: 2,
    billingAddressId: 2,
    paymentMethodId: 2,
    subtotal: "150.00",
    taxAmount: "5.00",
    shippingAmount: "10.00",
    discountAmount: "0.00",
    totalAmount: "165.00",
    notes: "Ready for fulfillment test order 2",
    version: 1,
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
];
