export const PAYMENT_TRANSACTIONS = [
  {
    orderId: 1,
    amount: "99.99",
    paymentMethodId: 1,
    paymentStatusId: 1,
    transactionReference: "TXN123456789",
    transactionDate: new Date("2024-01-15T10:00:00Z").toISOString(),
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },

  {
    orderId: 2,
    amount: "49.99",
    paymentMethodId: 2,
    paymentStatusId: 2,
    transactionReference: "TXN987654321",
    transactionDate: new Date("2024-01-15T10:00:00Z").toISOString(),
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },

  {
    orderId: 3,
    amount: "129.99",
    paymentMethodId: 1,
    paymentStatusId: 3,
    transactionReference: "TXN456789123",
    transactionDate: new Date("2024-01-15T10:00:00Z").toISOString(),
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
];
