export const SHELVES_DATA = [
  {
    rayonId: 1,
    columnLabel: "A",
    warehouseId: 1,
    description: "Left-most column of Rayon 1.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    rayonId: 1,
    columnLabel: "B",
    warehouseId: 1,
    description: "Second column of Rayon 1.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    rayonId: 2,
    columnLabel: "A",
    warehouseId: 1,
    description: "Left-most column of Rayon 2.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    rayonId: 2,
    columnLabel: "B",
    warehouseId: 1,
    description: "Second column of Rayon 2.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    rayonId: 3,
    columnLabel: "A",
    warehouseId: 2,
    description: "Left-most column of Rayon 3.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    rayonId: 3,
    columnLabel: "B",
    warehouseId: 2,
    description: "Second column of Rayon 3.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    rayonId: 4,
    columnLabel: "A",
    warehouseId: 2,
    description: "Left-most column of Rayon 4.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    rayonId: 4,
    columnLabel: "B",
    warehouseId: 2,
    description: "Second column of Rayon 4.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  // Extra column for testing
  {
    id: 99,
    rayonId: 1,
    columnLabel: "C",
    warehouseId: 1,
    description: "Third column of Rayon 1, added for testing.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
];
