export const SHIPPING_LABELS = [
  {
    packageId: 1,
    shippingTypeId: 1,
    shippingPriorityCodeId: 1,
    netWeight: "2.5",
    purchasedBy: 1,
    additionalNotes: "Normal package - handle with care",
    customerFirstName: "John",
    customerLastName: "Doe",
    address: "123 Main St",
    country: "USA",
    city: "New York",
  },
  {
    packageId: 2,
    shippingTypeId: 2,
    shippingPriorityCodeId: 2,
    netWeight: "1.0",
    purchasedBy: 2,
    additionalNotes: "Fragile item - glassware",
    customerFirstName: "Jane",
    customerLastName: "Smith",
    address: "456 Oak Ave",
    country: "USA",
    city: "Los Angeles",
  },
  {
    packageId: 4,
    shippingTypeId: 2,
    shippingPriorityCodeId: 2,
    netWeight: "1.0",
    purchasedBy: 2,
    additionalNotes: "Normal package - handle with care",
    customerFirstName: "Michael",
    customerLastName: "Johnson",
    address: "789 Pine Rd",
    country: "USA",
    city: "Chicago",
  },
  {
    packageId: 5,
    shippingTypeId: 2,
    shippingPriorityCodeId: 1,
    netWeight: "1.0",
    purchasedBy: 1,
    additionalNotes: "Fragile item - glassware",
    customerFirstName: "Emily",
    customerLastName: "Brown",
    address: "321 Elm St",
    country: "USA",
    city: "Houston",
  },
  {
    packageId: 6,
    shippingTypeId: 1,
    shippingPriorityCodeId: 2,
    netWeight: "1.0",
    purchasedBy: 2,
    additionalNotes: "Normal package - handle with care",
    customerFirstName: "William",
    customerLastName: "Davis",
    address: "654 Maple Dr",
    country: "USA",
    city: "Phoenix",
  },
];
