export const STORAGE_DATA = [
  {
    binId: 1,
    entryId: 8,
    quantity: 3,
    action: true, // true for ENTERED
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 1,
    entryId: 7,
    quantity: 1,
    action: true, // true for PLACE
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  // ...
  {
    binId: 2,
    entryId: 6,
    quantity: 5,
    action: false, // false for PICK
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 2,
    entryId: 5,
    quantity: 5,
    action: true, // true for ENTERED
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 3,
    entryId: 5,
    quantity: 2,
    action: false, // false for PICK
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 4,
    entryId: 4,
    quantity: 4,
    action: false, // false for PICK
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 5,
    entryId: 3,
    quantity: 6,
    action: false, // false for PICK
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 6,
    entryId: 2,
    quantity: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 7,
    entryId: 1,
    quantity: 8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 8,
    entryId: 9,
    quantity: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 9,
    entryId: 10,
    quantity: 7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 10,
    entryId: 11,
    quantity: 9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 11,
    entryId: 12,
    quantity: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 12,
    entryId: 13,
    quantity: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  {
    binId: 13,
    entryId: 14,
    quantity: 2,
    action: false, // false for PICK
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: null,
  },
  // {
  //   binId: 14,
  //   entryId: 15,
  //   quantity: 5,
  //   createdAt: new Date().toISOString(),
  //   updatedAt: new Date().toISOString(),
  //   createdBy: 1,
  //   updatedBy: null,
  // },

];
