import { PKG_ENTRIES, SERIES_ENTRIES } from "./entries/entries.constants";
import { TransferStatusIds } from "./transfer-statuses.constants";

export const WAREHOUSE_TRANSFERS_DATA = [
  {
    id: 2,
    entryId: SERIES_ENTRIES[0].id, // Series
    sourceWarehouseId: 1,
    destinationWarehouseId: 2,
    statusId: TransferStatusIds.SENT,
    transferDate: new Date().toISOString(),
    transferCode: "WT_02",
    notes: " Transfer Back",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    initiatedBy: 2,
  },
  {
    id: 3,
    entryId: SERIES_ENTRIES[1].id, // Series
    sourceWarehouseId: 2,
    destinationWarehouseId: 1,
    statusId: TransferStatusIds.SENT,
    transferDate: new Date().toISOString(),
    transferCode: "WT_03",
    notes: "Initial transfer",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    initiatedBy: 2,
  },
  {
    id: 4,
    entryId: SERIES_ENTRIES[2].id, // Series
    sourceWarehouseId: 2,
    destinationWarehouseId: 1,
    statusId: TransferStatusIds.SENT,
    transferDate: new Date().toISOString(),
    transferCode: "WT_04",
    notes: "Initial transfer",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    initiatedBy: 2,
  },
  {
    id: 6,
    entryId: PKG_ENTRIES[0].id, // Package
    sourceWarehouseId: 1,
    destinationWarehouseId: 2,
    statusId: TransferStatusIds.SENT,
    transferDate: new Date().toISOString(),
    transferCode: "WT_06",
    notes: "Move package to W1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    initiatedBy: 3,
  },
  {
    id: 7,
    entryId: PKG_ENTRIES[1].id, // Package
    sourceWarehouseId: 1,
    destinationWarehouseId: 2,
    statusId: TransferStatusIds.SENT,
    transferDate: new Date().toISOString(),
    transferCode: "WT_07",
    notes: "Move package to W2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 1,
    updatedBy: 1,
    initiatedBy: 1,
  },
  {
    id: 8,
    entryId: PKG_ENTRIES[2].id, // Package
    sourceWarehouseId: 1,
    destinationWarehouseId: 2,
    statusId: TransferStatusIds.SENT,
    transferDate: new Date().toISOString(),
    transferCode: "WT_08",
    notes: "Move package to W2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 2,
    updatedBy: 1,
    initiatedBy: 2,
  },
];
