import type { Table } from "drizzle-orm";

import * as schema from "@/db/models";

/**
 * Centralized list of all database tables.
 * Used for operations like truncating, seeding, and resetting sequences.
 *
 * Note: Tables are ordered to respect foreign key dependencies.
 * Parent tables should come before child tables.
 */
export const allTables: Table[] = [
  schema.countries,
  schema.cities,
  schema.entities,
  schema.operations,
  schema.users,
  schema.refreshTokens,
  schema.resetTokens,
  schema.roles,
  schema.permissions,
  schema.employees,
  schema.drivers,
  schema.entryTypes,
  schema.paymentMethodTypes,
  schema.paymentTypes,
  schema.paymentMethods,
  schema.addressTypes,
  schema.attributeTypes,
  schema.attributes,
  schema.colors,
  schema.sizes,
  schema.materialTypes,
  schema.designPatterns,
  schema.notificationTypes,
  schema.products,
  schema.productsHistory,
  schema.variants,
  schema.variantImages,
  schema.categories,
  schema.stores,
  schema.productTags,
  schema.tags,
  schema.productCategories,
  schema.productStoreTypes,
  schema.productNewArrivals,
  schema.newArrivals,
  schema.warehouses,
  schema.addresses,
  schema.entryStates,
  schema.entries,
  schema.entryHistory,
  schema.entryProducts,
  schema.bundles,
  schema.series,
  schema.items,
  schema.packages,
  schema.packageItems,
  schema.packageItemsHistory,
  schema.packageStatuses,
  schema.customers,
  schema.suppliers,
  schema.retailers,
  schema.returns,
  schema.reviews,
  schema.reviewStatuses,
  schema.discounts,
  schema.discountTypes,
  schema.groupApprovalStatuses,
  schema.groupCriteriaTypes,
  schema.ongoingGroups,
  schema.ongoingGroupRequests,
  schema.orderStatuses,
  schema.orderTypes,
  schema.orders,
  schema.orderItems,
  schema.orderFulfillmentStatuses,
  schema.orderItemFulfillmentStatuses,
  schema.transferStatuses,
  schema.recipientTypes,
  schema.notificationFrequencies,
  schema.notifications,
  schema.testimonials,
  schema.fulfillmentStates,
  schema.shippingTypes,
  schema.shippingPriorityCodes,
  schema.shippingLabels,
  schema.paymentStatuses,
  schema.paymentTransactions,
  schema.warehouseTransfers,
  schema.warehouseTransfersHistory,
  schema.rayons,
  schema.shelves,
  schema.bins,
  schema.storage,
  schema.faqs,
  schema.banners,
  schema.aboutUs,
  schema.filters,
  schema.directOrderProducts,
  schema.dropshippingProducts,
].filter(Boolean); // Filter out any undefined tables
